<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LfDateManager\Module'                        => __DIR__ . '/Module.php',
    'LfDateManager\Controller\LfDateManagerController' => __DIR__ . '/src/LfDateManager/Controller/LfDateManagerController.php',
    'LfDateManagerTest\Framework\TestCase'        => __DIR__ . '/tests/LfDateManager/Framework/TestCase.php',
    'LfDateManagerTest\SampleTest'                => __DIR__ . '/tests/LfDateManager/SampleTest.php',
);
